apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: master
  name: 99-master-ssh-enable-password-login
spec:
  config:
    ignition:
      version: 3.2.0
    storage:
      files:
        - contents:
            source: data:;base64,UGFzc3dvcmRBdXRoZW50aWNhdGlvbiB5ZXMKUGVybWl0Um9vdExvZ2luIHllcwo=
          mode: 420
          overwrite: true
          path: /etc/ssh/sshd_config.d/20-enable-passwords.conf

