apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: worker
  name: 99-worker-pt
spec:
  kernelArguments:
    - intel_iommu=on
    - iommu=pt
